name: 'Setup R & Bioconductor'
inputs:
  bioc-version:
    description: 'Version of Bioconductor'
    required: true
    default: 'devel'
runs:
  using: "composite"
  steps:
  - id: find-r-version
    run: |
      RVERSION=`"${{ github.action_path }}"/bioc-to-r-map.sh ${{ inputs.bioc-version }}`
      echo "::set-output name=r-version::$(echo ${RVERSION})"
    shell: bash
  - uses: r-lib/actions/setup-r@v2
    with:
      r-version: ${{ steps.find-r-version.outputs.r-version }}
      Ncpus: 2
      use-public-rspm: true
  - run: wget https://bioconductor.org/checkResults/${{ inputs.bioc-version }}/bioc-LATEST/Renviron.bioc -O ${HOME}/.Renviron
    shell: bash
  - run: |
      install.packages(c("BiocManager", "remotes"))
      BiocManager::install(version = "${{ inputs.bioc-version }}" )
    shell: Rscript {0}
  - run: |
      Sys.getenv()
    shell: Rscript {0}
    