name: 'Setup R & Bioconductor'
inputs:
  bioc-version:
    description: 'Version of Bioconductor'
    required: true
    default: 'devel'
runs:
  using: "composite"
  steps:
  - id: find-r-version
    run: echo "::set-output name=r-version::$(./bioc-to-r-map.sh ${{ inputs.bioc-version }})"
    shell: bash
  - uses: r-lib/actions/setup-r@v2
    with:
      r-version: ${{ steps.find-r-version.outputs.r-version }}
      Ncpus: 2
      use-public-rspm: true
  - run: |
      install.packages("BiocManager", dependencies = TRUE)
      BiocManager::install(version = ${{ steps.find-r-version.outputs.r-version }} )
    shell: Rscript {0}