name: 'Setup R & Bioconductor'
inputs:
  bioc-version:
    description: 'Version of Bioconductor'
    required: true
    default: 'devel'
  bioc-mirror:
    description: ''
    required: false
    default: 'https://www.bioconductor.org'
  rtools-version:
    description: ''
    required: false
    default: 42
runs:
  using: "composite"
  steps:
  - id: find-versions
    run: |
      RVERSION=$(Rscript "${{ github.action_path }}/get-r-version.sh" "${{ github.action_path }}/bioc-version-map.csv" ${{ inputs.bioc-version }} r_version)
      RTOOLS=$(Rscript "${{ github.action_path }}/get-r-version.sh" "${{ github.action_path }}/bioc-version-map.csv" ${{ inputs.bioc-version }} rtools)
      BIOCVERSION=`"${{ github.action_path }}/bioc-version-check.sh" ${{ inputs.bioc-version }}`
      echo "::set-output name=r-version::$(echo ${RVERSION})"
      echo "::set-output name=rtools-version::$(echo ${RVERSION})"
      echo "::set-output name=bioc-version::$(echo ${BIOCVERSION})"
    shell: bash
  - uses: r-lib/actions/setup-r@v2
    with:
      r-version: ${{ steps.find-versions.outputs.r-version }}
      Ncpus: 2
      use-public-rspm: true
      rtools-version: ${{ steps.find-versions.outputs.rtools-version }}
  - name: Download Renviron
    run: |
      download.file('https://bioconductor.org/checkResults/${{ inputs.bioc-version }}/bioc-LATEST/Renviron.bioc', destfile = '~/.Renviron', mode = 'wb')
    shell: Rscript {0}
  - name: Setting Bioconductor mirror
    run: |
      write('options(BioC_mirror = "${{ inputs.bioc-mirror }}")', file = '~/.Rprofile', append = TRUE)
    shell: Rscript {0}
  - name: Install and initialize BiocManager
    run: |
      install.packages(c("BiocManager", "remotes"))
      BiocManager::install(version = "${{ steps.find-versions.outputs.bioc-version }}" )
    shell: Rscript {0}
