name: 'Run BiocCheck'
inputs:
  package-directory:
    description: 'Specify the location of the package to check if it is not in the working directory.'
    required: false
    default: '.'
  error-on:
    description: 'Specify the level of issue that should cause the action to fail.'
    required: false
    default: 'error'
  arguments:
    description: 'Arguments provided to BiocCheck() to disable specific tests.'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
  
    - name: Test for docker
      run: echo ${BIOCONDUCTOR_DOCKER_VERSION} >> ${GITHUB_ENV}
      shell: bash
  
    - name: Install system dependencies
      if: ${{ (runner.os == 'Linux') && (env.BIOCONDUCTOR_DOCKER_VERSION == '') }}
      run: |
        echo ${{ env.BIOCONDUCTOR_DOCKER_VERSION }}
        sudo apt-get update && sudo apt-get -y -qq install libcurl4-openssl-dev
      shell: bash
      
    - run: |
        if(!requireNamespace("BiocManager", quietly = TRUE)) { install.packages("BiocManager", quiet = TRUE) }
        BiocManager::install('BiocCheck', quiet = TRUE, upgrade = FALSE, ask = FALSE)
      shell: Rscript {0}
      
    - run: |
        Rscript --vanilla "${GITHUB_ACTION_PATH}/run-bioc-check.R" "${{ inputs.package-directory }}" "${{ inputs.error-on }}" ${{ inputs.arguments }}
      shell: bash
