on:
  push:
    tags:
      - 'v1'
  workflow_dispatch:
   
name: Trigger Test Workflows

jobs:
  trigger-tests:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Trigger example package build
      env:
        TOKEN: ${{ secrets.MY_TOKEN }}
      run: |
        curl -X POST -H "Authorization: token $TOKEN" "https://api.github.com/repos/grimbough/biocActionsExamples/actions/workflows/example-workflow.yml/dispatches" -d '{"ref":"main"}'