on:
  workflow_dispatch:
  schedule:
  # should run at midnight on the first day of each month
    - cron:  '0 0 1 * *'
   
name: Update Version Map

env:
  R_LIBS_USER: /tmp/R-lib

jobs:
  update-map:
    runs-on: ubuntu-20.04
    
    steps:
    
    - name: Make library folder
      run: mkdir -p "${{ env.R_LIBS_USER }}"
      shell: bash

    - name: Checkout github repo
      uses: actions/checkout@v2
      
    - name: Install BiocManager
      run: |
        .libPaths()
        install.packages('BiocManager', repos = 'https://cran.rstudio.com/')
      shell: Rscript {0}
      
    - name: Run update
      run: ${{ GITHUB_WORKSPACE }}/setup-bioc/create-version-map.R
      shell: Rscript {0}
      working-directory: ${{ GITHUB_WORKSPACE }}/setup-bioc
