on:
  workflow_dispatch:
  schedule:
  # should run at midnight on the first day of each month
    - cron:  '0 0 1 * *'
   
name: Update Version Map



jobs:
  update-map:
    runs-on: ubuntu-20.04
    
    steps:
    
    - name: Make library folder
      run: |
        echo "R_LIBS_USER=${{ runner.temp }}/R-lib" >> $GITHUB_ENV
        mkdir -p ${{ runner.temp }}/R-lib
      shell: bash

    - name: Checkout github repo
      uses: actions/checkout@v2
      
    - name: Install BiocManager
      run: |
        .libPaths()
        install.packages('BiocManager', repos = 'https://cran.rstudio.com/')
      shell: Rscript {0}
      
    - name: Run update
      run: Rscript ${{ github.workspace }}/setup-bioc/create-version-map.R
      shell: bash
      working-directory: ${{ github.workspace }}/setup-bioc
