on:
  workflow_dispatch:
  schedule:
  # should run at midnight on the first day of each month
    - cron:  '0 0 1 * *'
   
name: Update Version Map

jobs:
  update-map:
    runs-on: ubuntu-20.04
    
    steps:
    
    - name: Make library folder
      run: |
        echo "R_LIBS_USER=${{ runner.temp }}/R-lib" >> $GITHUB_ENV
        mkdir -p ${{ runner.temp }}/R-lib
      shell: bash

    - name: Checkout github repo
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0
      
    - name: Install BiocManager
      run: |
        .libPaths()
        install.packages('BiocManager', repos = 'https://cran.rstudio.com/')
      shell: Rscript {0}
      
    - name: Run update
      run: Rscript ${{ github.workspace }}/setup-bioc/create-version-map.R
      shell: bash
      working-directory: ${{ github.workspace }}/setup-bioc
      
    - name: Commit updated version map
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add setup-bioc/bioc-version-map.csv
        git commit -m "`date +%B` update" || echo "No changes to commit"
        git tag -d v1 && git tag v1 && git push origin :v1 && git push origin v1 || echo "No changes to commit"
    
    - name: Update tag test
      uses: phish108/autotag-action@1.1.37
      id: taggerTest
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        branch: v1-branch
        dry-run: 'true'

